sudo: false
dist: trusty
language: cpp

compiler:
  - gcc

os:
  - osx

before_install:
  # work-around for issue https://github.com/travis-ci/travis-ci/issues/6307
  # might not be necessary in the future
  command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  rvm get stable

before_script:
- cmake .

script:
- make 99 101 107 108 110 124 145 222 234 235 236 250 298 337 366
- ./99
- ./101
- ./107
- ./108
- ./110
- ./124
- ./145
- ./222
- ./234
- ./235
- ./236
- ./250
- ./298
- ./337
- ./366