sudo: false
dist: trusty
matrix:
  include:
    - language: cpp
      compiler: gcc
      os: osx
      before_script:
        - cmake .
      env:
        - BLD_DIR=$(pwd)/cmake-build-debug
      script:
        - make all
        - cd $BLD_DIR/leetcode/
        - "for a in $(ls | grep '^[0-9]*$'); do ./$a; done"
        - cd $BLD_DIR/misc/
        - "for a in $(ls | grep '^[0-9]*$'); do ./$a; done"

    - language: rust
      rust: nightly
      os: osx
      script:
       - cd rust/ && cargo test

    - language: go
      go: 1.12.x
      script:
        - go test ./...
