sudo: false
dist: trusty
matrix:
  include:
    - language: cpp
      compiler: gcc
      os: osx
      script:
        - ./testall.sh

    - language: rust
      rust: nightly
      os: osx
      script:
       - cd rust/ && cargo test

    - language: go
      go: 1.12.x
      script:
        - go test ./...
