sudo: false
dist: trusty
matrix:
  include:
    - language: cpp
      compiler: gcc
      os: osx
      before_script:
       - cmake .
      script:
       - make all
       - "for a in $(ls | grep '^[0-9]*$'); do ./$a; done"

    - language: rust
      rust: nightly
      os: osx
      script:
       - pwd
       - cd rust/ && cargo test    