/*          
 * [Source] 
 *          
 * https://leetcode.com/problems/find-the-difference/#/description
 *          
 * [Problem Description]
 *          
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 *          
 * [Comments]
 *
 * while(s[i])    <--- work with char* w/o knowing the length of char* in C.
 * int i=0, j=0;  <--- declare mutiple variables in one line
 * Very clever solution in general
 *
 * [Companies]
 */          

char findTheDifference(char* s, char* t) {
  int i=0,j=0;
  int sum1=0,sum2=0;
  char result;
  while(s[i])
  {
    sum1+=s[i];
    i++;
  }
  while(t[j])
  {
    sum2+=t[j];
    j++;
  }
  result=(char)(sum2-sum1);
  return result;
}

