sudo: false
dist: trusty
matrix:
  include:
    - language:
        - cpp
        - python3
      compiler: gcc
      os: osx
      script:
        - python3 testall.py
        - cd cmake-build-debug && ctest

    - language: rust
      rust: nightly
      os: osx
      script:
       - cd rust/ && cargo test

    - language: go
      go: 1.12.x
      script:
        - go test ./...
